// modules/talents.js

export const TALENT_GRID_CONFIG = {
    // --- CORE CONSTALLATION (Always Visible) ---
    core: {
        'core-nexus': {
            id: 'core-nexus',
            name: 'Core Nexus',
            description: (rank, maxed) => 'The heart of the Ascension Conduit. Unlocks the primary constellations.',
            icon: '💠',
            maxRanks: 1,
            costPerRank: [1],
            position: { x: 50, y: 5 },
            prerequisites: [],
            isNexus: true,
        },
        'overload-protocol': {
            id: 'overload-protocol',
            name: 'Capstone: Overload Protocol',
            description: () => 'When your inventory is full, picking up a power-up instantly uses it instead of discarding it.',
            icon: '⚛️',
            maxRanks: 1,
            costPerRank: [50],
            position: { x: 50, y: 95 },
            prerequisites: ['phase-momentum', 'unstable-singularity', 'energetic-recycling'],
            isNexus: true,
        }
    },

    // --- AEGIS CONSTALLATION (Defense & Survival) ---
    aegis: {
        color: 'var(--primary-glow)',
        'exo-weave-plating': {
            id: 'exo-weave-plating',
            name: 'Exo-Weave Plating',
            description: (rank, maxed) => maxed
                ? 'Increases Max Health by a total of 60.'
                : `Increases Max Health by ${[15, 20, 25][rank-1] || 0}.`,
            icon: '❤️',
            maxRanks: 3,
            costPerRank: [1, 2, 2],
            position: { x: 30, y: 25 },
            prerequisites: ['core-nexus'],
        },
        'aegis-shield': {
            id: 'aegis-shield',
            name: 'Extended Capacitor',
            powerPrerequisite: 'shield',
            description: (rank, maxed) => maxed
                ? 'Shield power-up duration is increased by a total of 3 seconds.'
                : `Increases Shield power-up duration by 1.5s.`,
            icon: '⏱️',
            maxRanks: 2,
            costPerRank: [1, 1],
            position: { x: 20, y: 40 },
            prerequisites: ['exo-weave-plating'],
        },
        'cryo-shatter': {
            id: 'aegis-freeze',
            name: 'Cryo-Shatter',
            powerPrerequisite: 'freeze',
            description: (rank, maxed) => `Enemies defeated while Frozen have a ${maxed ? '50%' : '25%'} chance to shatter, dealing area damage.`,
            icon: '❄️',
            maxRanks: 2,
            costPerRank: [2, 2],
            position: { x: 10, y: 55 },
            prerequisites: ['aegis-shield'],
        },
        'solar-wind': { // NAME UPDATED
            id: 'fleet-footed',
            name: 'Solar Wind',
            description: (rank, maxed) => maxed
                ? 'Base movement speed is increased by a total of 12%.'
                : `Increases base movement speed by 6%.`,
            icon: '🏃',
            maxRanks: 2,
            costPerRank: [1, 2],
            position: { x: 40, y: 45 },
            prerequisites: ['exo-weave-plating'],
        },
        'reactive-plating': {
            id: 'reactive-plating',
            name: 'Reactive Plating',
            description: (rank, maxed) => `Taking heavy damage automatically grants a temporary Shield for ${maxed ? '3s' : '1.5s'}. This effect can only occur once every 30 seconds.`,
            icon: '⚡',
            maxRanks: 2,
            costPerRank: [2, 3],
            position: { x: 30, y: 60 },
            prerequisites: ['solar-wind'],
        },
        'contingency-protocol': {
            id: 'contingency-protocol',
            name: 'Contingency Protocol',
            description: () => 'Once per stage, taking fatal damage instead sets your Health to 1 and grants 3s of invulnerability.',
            icon: '💪',
            maxRanks: 1,
            costPerRank: [4],
            position: { x: 5, y: 75 },
            prerequisites: ['cryo-shatter'],
        },
        'phase-momentum': {
            id: 'phase-momentum',
            name: 'Capstone: Phase Momentum',
            description: () => 'After avoiding damage for 8s, gain +10% speed & move through non-boss enemies.',
            icon: '👻',
            maxRanks: 1,
            costPerRank: [3],
            position: { x: 30, y: 80 },
            prerequisites: ['reactive-plating'],
        }
    },
    
    // --- HAVOC CONSTALLATION (Offense & Destruction) ---
    havoc: {
        color: '#ff8800',
        'high-frequency-emitters': {
            id: 'high-frequency-emitters',
            name: 'High-Frequency Emitters',
            description: (rank, maxed) => maxed
                ? 'All damage is increased by a total of 12%.'
                : `Increases all damage by ${[5, 7][rank-1] || 0}%.`,
            icon: '📈',
            maxRanks: 2,
            costPerRank: [1, 2],
            position: { x: 70, y: 25 },
            prerequisites: ['core-nexus'],
        },
        'stellar-detonation': {
            id: 'havoc-missile',
            name: 'Stellar Detonation',
            powerPrerequisite: 'missile',
            description: (rank, maxed) => `Increases the explosion radius of the Missile power by ${maxed ? '30%' : '15%'}.`,
            icon: '💥',
            maxRanks: 2,
            costPerRank: [1, 1],
            position: { x: 60, y: 40 },
            prerequisites: ['high-frequency-emitters'],
        },
        'homing-shrapnel': {
            id: 'seeking-shrapnel',
            name: 'Homing Shrapnel',
            powerPrerequisite: 'missile',
            description: () => 'Your Missile power now releases a volley of seeking shrapnel upon impact.',
            icon: '🧭',
            maxRanks: 1,
            costPerRank: [2],
            position: { x: 55, y: 58 },
            prerequisites: ['stellar-detonation'],
        },
        'arc-cascade': { // NAME UPDATED
            id: 'havoc-chain',
            name: 'Arc Cascade',
            powerPrerequisite: 'chain',
            description: (rank, maxed) => maxed
                ? 'Chain Lightning jumps to 2 additional targets.'
                : `Chain Lightning jumps to 1 additional target.`,
            icon: '⛓️',
            maxRanks: 2,
            costPerRank: [1, 1],
            position: { x: 70, y: 65 },
            prerequisites: ['homing-shrapnel'],
        },
        'amplified-wavefront': {
            id: 'havoc-shockwave',
            name: 'Amplified Wavefront',
            powerPrerequisite: 'shockwave',
            description: (rank, maxed) => `Increases the radius and travel speed of the Shockwave power by ${maxed ? '30%' : '15%'}.`,
            icon: '🌐',
            maxRanks: 2,
            costPerRank: [2, 2],
            position: { x: 80, y: 55 },
            prerequisites: ['arc-cascade'],
        },
        'unstoppable-frenzy': {
            id: 'havoc-berserk',
            name: 'Unstoppable Frenzy',
            powerPrerequisite: 'berserk',
            description: () => 'While Berserk is active, you are immune to all Slow and Stun effects.',
            icon: '💢',
            maxRanks: 1,
            costPerRank: [3],
            position: { x: 90, y: 40 },
            prerequisites: ['high-frequency-emitters'],
        },
        'overcharged-capacitors': {
            id: 'overcharged-capacitors',
            name: 'Overcharged Capacitors',
            description: () => 'Increases all damage dealt by 15%, but also increases all damage received by 15%.',
            icon: '⚠️',
            maxRanks: 1,
            costPerRank: [3],
            position: { x: 85, y: 70 },
            prerequisites: ['amplified-wavefront', 'unstoppable-frenzy'],
        },
        'unstable-singularity': {
            id: 'unstable-singularity',
            name: 'Capstone: Unstable Singularity',
            powerPrerequisite: 'black_hole',
            description: () => 'Enemies are damaged when pulled into the Black Hole. Explodes on expiry.',
            icon: '⚫',
            maxRanks: 1,
            costPerRank: [3],
            position: { x: 70, y: 85 },
            prerequisites: ['overcharged-capacitors'],
        },
    },

    // --- FLUX CONSTALLATION (Utility & Mastery) ---
    flux: {
        color: 'var(--secondary-glow)',
        'essence-conduit': {
            id: 'essence-conduit',
            name: 'Essence Conduit',
            description: (rank, maxed) => maxed
                ? 'Gain 25% more Essence from all sources.'
                : `Gain ${[10, 15][rank-1] || 0}% more Essence (XP).`,
            icon: '💰',
            maxRanks: 2,
            costPerRank: [1, 2],
            position: { x: 50, y: 25 },
            prerequisites: ['core-nexus'],
        },
        'resonance-magnet': {
            id: 'resonance-magnet',
            name: 'Resonance Magnet',
            description: (rank, maxed) => maxed
                ? 'Increases pickup radius by a total of 150px.'
                : `Increases pickup radius by 75px.`,
            icon: '🧲',
            maxRanks: 2,
            costPerRank: [1, 1],
            position: { x: 50, y: 40 },
            prerequisites: ['essence-conduit'],
        },
        'temporal-anomaly': {
            id: 'temporal-anomaly',
            name: 'Temporal Anomaly',
            description: (rank, maxed) => `Power-ups decay ${maxed ? '50%' : '25%'} slower, remaining on the field longer.`,
            icon: '⏳',
            maxRanks: 2,
            costPerRank: [1, 2],
            position: { x: 40, y: 55 },
            prerequisites: ['resonance-magnet'],
        },
        'quantum-duplicate': {
            id: 'quantum-duplicate',
            name: 'Quantum Duplicate',
            powerPrerequisite: 'decoy',
            description: () => `Your Decoy now actively moves away from your position, drawing enemy aggression more effectively.`,
            icon: '👥',
            maxRanks: 1,
            costPerRank: [2],
            position: { x: 60, y: 55 },
            prerequisites: ['resonance-magnet'],
        },
        'temporal-collapse': {
            id: 'temporal-collapse',
            name: 'Mastery: Temporal Collapse',
            powerPrerequisite: 'gravity',
            description: () => 'The Gravity Well power-up now collapses into a lingering field that slows enemies.',
            icon: '🌪️',
            maxRanks: 1,
            costPerRank: [3],
            position: { x: 65, y: 70 },
            prerequisites: ['quantum-duplicate'],
        },
        'preordinance': {
            id: 'preordinance',
            name: 'Preordinance',
            description: () => 'The first power-up you use each stage is duplicated, as if affected by the "Stack" power-up.',
            icon: '🎲',
            maxRanks: 1,
            costPerRank: [4],
            position: { x: 35, y: 70 },
            prerequisites: ['temporal-anomaly'],
        },
        'energetic-recycling': {
            id: 'energetic-recycling',
            name: 'Capstone: Energetic Recycling',
            description: () => `Using a power-up has a 20% chance that it is not consumed.`,
            icon: '♻️',
            maxRanks: 1,
            costPerRank: [4],
            position: { x: 50, y: 85 },
            prerequisites: ['preordinance', 'temporal-collapse'],
        },
    }
};
