name: Test Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello from your self-hosted runner on ${{ runner.os }}!"
