name: Local Pages Check

on:
  push:
    branches:
      - main

jobs:
  pages:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: echo "Local runner processed push to main"
